analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 258541,\\n  \\"name\\"\: \\"Mobile\\",\\n  \\"teamId\\"\: 220973,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 220973,\\n    \\"name\\"\: \\"First Team\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 281336,\\n      \\"name\\"\: \\"TELKOMSEL\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 220973,\\n  \\"name\\"\: \\"First Team\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 281336,\\n    \\"name\\"\: \\"TELKOMSEL\\",\\n    \\"samlSSO\\"\: false\\n  }\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
