<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Tanda Tangan Digital_sigPadRef</name>
   <tag></tag>
   <elementGuidId>2b89c4df-83e9-46f5-a366-36a3fe90ce51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.sigPadRef</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>a75237d1-9598-4bb3-8071-d8673ee3d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sigPadRef</value>
      <webElementGuid>b67f6dc4-bc7d-435e-a343-f1e97888256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>ae1845b9-2b40-4428-b554-81a8cc494c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>269</value>
      <webElementGuid>e09d0692-c32f-43bc-8aaa-c1554b45bccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout custom-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;form-card mx-auto card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0&quot;]/div[@class=&quot;d-flex flex-column col-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ttd-card mb-2 card&quot;]/div[1]/div[@class=&quot;p-0 position-relative card-body&quot;]/canvas[@class=&quot;sigPadRef&quot;]</value>
      <webElementGuid>d8fe2daf-3546-4639-a3a8-3d22b3700de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/div/canvas</value>
      <webElementGuid>fed72a02-655f-4c45-9243-c44fcea3d115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>caa8e054-9de3-4d52-8f50-f5eb18d987af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
