<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor KTP_nomor_ktp</name>
   <tag></tag>
   <elementGuidId>cf381707-fbf5-4e05-9645-49df9bc5f1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nomor_ktp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nomor_ktp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nomor KTP anda...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba0fc5cc-8e1c-4e45-9c09-b68c1dae0e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70a6f3e3-b940-4b80-b009-bfb0e2c5b0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02587749-f690-4d22-afff-7211e3007664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_ktp</value>
      <webElementGuid>aae0603d-8963-46e9-9148-243dfecbca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nomor KTP anda...</value>
      <webElementGuid>ff985f6c-c848-45e9-b8ae-b79cd0d3e7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout flex-row align-items-center bg_image&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;container ml-0 my-5&quot;]/div[@class=&quot;justify-content-between row&quot;]/div[@class=&quot;mx-auto col-md-10&quot;]/div[@class=&quot;card shadow-lg&quot;]/div[@class=&quot;card-body py-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-2 mx-2&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>72fac207-106d-47dc-af1d-75c2377c6b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nomor_ktp']</value>
      <webElementGuid>3d62fe14-0d74-4d67-b720-dfdabd898a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>bd8360ed-a5cb-429f-b3a2-bb62118527bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/input</value>
      <webElementGuid>c0303b0b-2754-4904-8113-8a49f9d228c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nomor_ktp' and @placeholder = 'Masukkan nomor KTP anda...']</value>
      <webElementGuid>e4599a1e-644d-4068-8d91-5593eae60c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
