<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AdminyanragaTris Retno Ary_2b9beb</name>
   <tag></tag>
   <elementGuidId>adfa598f-52b4-432e-8f14-9618fb633ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9592ca68-447f-4039-ad5c-6769a1b2266a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d201a818-2bc2-4ea2-bb05-8a7d9739e4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_pic</value>
      <webElementGuid>1b4a209b-712a-442a-91df-1b3174a549b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruTest 321SUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriandi pmAhlan RezkiAgus Setyaadnan111</value>
      <webElementGuid>89cf6c3b-0136-41dc-8e4b-c098c13a41c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout custom-layout&quot;]/div[@class=&quot;c-wrapper&quot;]/div[@class=&quot;c-body&quot;]/main[@class=&quot;c-main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;fade show&quot;]/div[@class=&quot;container-mains&quot;]/div[@class=&quot;form-card mx-auto card&quot;]/div[@class=&quot;mb-4 card-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row form-group my-0&quot;]/div[@class=&quot;d-flex flex-column col-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>2d5cb72e-4698-44c5-9230-24cbfb12cbbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>9b245a3d-1bc2-4109-9ce3-1def817154ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>dcc5280b-ddd3-4117-9819-62839467ede6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>1d7d7c68-5069-4c71-baf2-ec792439aa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evidance'])[1]/following::select[1]</value>
      <webElementGuid>bc3bc189-79d0-44e3-af19-d677ca26f2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Lembur'])[1]/preceding::select[1]</value>
      <webElementGuid>e7c8f19a-6d2d-4f18-9d74-02288b8dd4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>22a0c635-72d9-4012-a868-ebed7ee25475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>7a360917-c54e-4ca6-a92f-749f7cc39d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'id_pic' and (text() = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruTest 321SUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriandi pmAhlan RezkiAgus Setyaadnan111' or . = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT test nama lengkapTest Karyawan BaruTest 321SUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRatnaRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriandi pmAhlan RezkiAgus Setyaadnan111')]</value>
      <webElementGuid>a62abbad-c61b-4479-b878-c6664f4e626d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
