<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place Order</name>
   <tag></tag>
   <elementGuidId>d7bb5844-eb68-4651-87d4-ae67e4e32015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.place-order-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='openOrderModal()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0da26104-d91d-4888-9a61-177ea7949de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>place-order-btn</value>
      <webElementGuid>3ff6dcdb-dfe8-4f94-aecd-d2ae54a9a9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openOrderModal()</value>
      <webElementGuid>333e5711-53bb-4c1b-a84d-c8b447a27748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place Order →</value>
      <webElementGuid>e09066d8-cfcb-4443-9940-f5e6f2abc0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-footer&quot;)/button[@class=&quot;place-order-btn&quot;]</value>
      <webElementGuid>b153d16d-d4e4-4a1b-ba32-8d46d65a5639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='openOrderModal()']</value>
      <webElementGuid>19d00ab6-e560-4f33-9f0f-b11499f7c5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-footer']/button</value>
      <webElementGuid>46dd6c58-fda4-465d-adb5-f4dad2afc7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 70.497.000'])[1]/following::button[1]</value>
      <webElementGuid>841b8796-aef1-47b3-8fec-21048b6a8e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
      <webElementGuid>f3d942ac-eb51-430f-aad7-0db3699cbcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⚠️ Pilih warna terlebih dahulu!'])[1]/preceding::button[1]</value>
      <webElementGuid>cd04d7b3-6b88-4bd8-a7c6-bbf73cbae30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✕'])[7]/preceding::button[1]</value>
      <webElementGuid>d773ce22-b0c5-4151-8fde-3ee0315bcbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place Order →']/parent::*</value>
      <webElementGuid>455186d0-a8dc-4fef-95c8-95f9439d1849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>fa557444-b030-4f84-a1c8-6281706a24a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Place Order →' or . = 'Place Order →')]</value>
      <webElementGuid>8c6683bb-05b4-44ef-af96-a0a7afc4a70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
