<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>c61bb5f5-726d-4491-bbfc-9d22f6601bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-btn-add-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-btn-add-cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34f11a0e-7e6e-4644-bed1-d0185744a93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>6beef040-c36e-4215-b6a3-49c75ab55112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-btn-add-cart</value>
      <webElementGuid>d356937d-721c-4161-85f1-dae0ddc7e344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🛒 Add to Cart</value>
      <webElementGuid>aac06f52-319c-48ed-8a2c-5d28052cd1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-btn-add-cart&quot;)</value>
      <webElementGuid>98fd6ed6-37db-449c-80a7-59c40ae6f3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-btn-add-cart']</value>
      <webElementGuid>7ac0221f-b3a6-42b0-a612-f8c011ead345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-detail']/div/div[7]/button</value>
      <webElementGuid>c38ea5d8-e1b8-4085-9327-0a55747d9f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biru'])[1]/following::button[1]</value>
      <webElementGuid>f1f9b027-401c-4b8c-bf2c-b4bb45e1e3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitam'])[1]/following::button[1]</value>
      <webElementGuid>b3467655-93a9-4afa-8790-c42ed78a521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>377b6c14-a21a-4d22-b5eb-678e6a580279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🛒 Your Cart'])[1]/preceding::button[2]</value>
      <webElementGuid>f8d3914d-9024-4d8b-8280-0d4114de8c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🛒 Add to Cart']/parent::*</value>
      <webElementGuid>1c9980bf-e781-48e5-84b7-7608a5823f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>cc72ac99-9c9d-459d-8291-f7c15348ff9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-btn-add-cart' and (text() = '🛒 Add to Cart' or . = '🛒 Add to Cart')]</value>
      <webElementGuid>b223fb05-968a-44a5-9e15-aba54dad7424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
