<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aadmin</name>
   <tag></tag>
   <elementGuidId>51aba0dd-0d13-4c8b-a22e-61a9b2492220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.user-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-actions']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cfb6649-884b-4553-ad14-93cac4cfc220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-info</value>
      <webElementGuid>0e554b4f-4290-4ce4-9996-987b9eeb0322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aadmin</value>
      <webElementGuid>697bc31d-b37e-4803-b649-88c54993bc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-actions&quot;)/div[@class=&quot;user-info&quot;]</value>
      <webElementGuid>d72b1b8e-3c20-41fe-9944-8b7f1d31256e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-actions']/div</value>
      <webElementGuid>76a7d841-8b95-4ff7-a734-57a2d025ff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::div[1]</value>
      <webElementGuid>b0e0388a-873a-4c59-9784-71939bcd8efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::div[1]</value>
      <webElementGuid>8984a623-1f40-42aa-8957-82d896ea21dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>29a55a2b-88df-45e4-bf8d-759e1e74b001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Aadmin' or . = 'Aadmin')]</value>
      <webElementGuid>1f0f5611-4a52-475c-8fd3-aafe1006c330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
