<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month</name>
   <tag></tag>
   <elementGuidId>572b35f4-2a3c-4e6b-ac1a-bb3480752912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='order-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ce528be-f050-47dc-b120-8631d761344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-input</value>
      <webElementGuid>3394c883-1c5e-425b-b30c-d11631b974bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-month</value>
      <webElementGuid>9a3ba434-1132-4741-be1f-900c1eb036e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Month
          JanuaryFebruary
          MarchApril
          MayJune
          JulyAugust
          SeptemberOctober
          NovemberDecember
        </value>
      <webElementGuid>0f3f8932-651a-4c29-a94c-43c58e8ce242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-month&quot;)</value>
      <webElementGuid>10bf82b9-fdc2-4786-a615-f1ba3c6db41d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='order-month']</value>
      <webElementGuid>0b628937-d082-46db-b5fa-75b00c1c85b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-order']/div/div[7]/div/select</value>
      <webElementGuid>dd637688-a287-40ce-9038-1b737a03a042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📅'])[1]/following::select[1]</value>
      <webElementGuid>3d67c31e-3359-4a22-a0d2-3281a4cad26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='💳'])[1]/following::select[1]</value>
      <webElementGuid>83b71d49-f3da-4c1f-bcb9-76ded58868d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📅'])[2]/preceding::select[1]</value>
      <webElementGuid>dad47478-eee0-4c8b-bfe6-497a89eb64f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::select[2]</value>
      <webElementGuid>5637b489-89b9-4a58-aafb-53915ccfb226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>f2fa9e73-8ab6-4b94-af05-06f848915258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'order-month' and (text() = '
          Month
          JanuaryFebruary
          MarchApril
          MayJune
          JulyAugust
          SeptemberOctober
          NovemberDecember
        ' or . = '
          Month
          JanuaryFebruary
          MarchApril
          MayJune
          JulyAugust
          SeptemberOctober
          NovemberDecember
        ')]</value>
      <webElementGuid>789df6f5-18d9-4b2e-a764-ea01fdec4309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
