<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select City</name>
   <tag></tag>
   <elementGuidId>11aff5c5-4cf8-4aba-a0f7-0022e8ccb920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='order-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>336c04a5-15e1-428d-889d-1fc0bcd9b0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-input</value>
      <webElementGuid>7abf706d-a096-4b56-807e-1e8d86e07860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-city</value>
      <webElementGuid>7d89883c-7211-49de-bbf8-b28fa34fa693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CityJakartaSurabayaBandungMedanSemarangMakassarPalembangTangerangDepokBekasiYogyakartaDenpasar</value>
      <webElementGuid>b504fe44-e7d8-421c-9b2d-ae65bb601fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-city&quot;)</value>
      <webElementGuid>57ce3fee-7bd9-463c-8cf0-4adf7b42b332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='order-city']</value>
      <webElementGuid>2a2c79af-d80b-4ff8-855a-032ea9d51f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-order']/div/div[5]/select</value>
      <webElementGuid>adf05ed4-25d8-40f8-98f2-d907f8af25c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🏙️'])[1]/following::select[1]</value>
      <webElementGuid>1d6c6cfc-6bf9-485f-9dcf-719ad93b3045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌍'])[1]/following::select[2]</value>
      <webElementGuid>ec21230b-ec4c-47a3-871b-f795c8e1d1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='💳'])[1]/preceding::select[1]</value>
      <webElementGuid>9dbceb30-7491-443e-85bd-2fe1a572d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📅'])[1]/preceding::select[1]</value>
      <webElementGuid>aa319153-3518-4f12-a307-5d7cd087371b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>8de5172c-2bd5-4b75-9185-0c1214e0f061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'order-city' and (text() = 'Select CityJakartaSurabayaBandungMedanSemarangMakassarPalembangTangerangDepokBekasiYogyakartaDenpasar' or . = 'Select CityJakartaSurabayaBandungMedanSemarangMakassarPalembangTangerangDepokBekasiYogyakartaDenpasar')]</value>
      <webElementGuid>719a72d0-ebc9-4fcc-866a-943c8f5980c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
