<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year</name>
   <tag></tag>
   <elementGuidId>43db0ff4-6e40-4000-911c-6d6fb4eaec53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='order-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2d22029-55f9-4922-8402-f87231f5251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-input</value>
      <webElementGuid>91adc9e2-13d0-4a3d-96b5-94d4d4b23437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-year</value>
      <webElementGuid>ce59e91f-ec5d-49bb-96c7-533518155765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year2026202720282029203020312032203320342035203620372038203920402041</value>
      <webElementGuid>bd28ee0f-35aa-46a7-98dd-3768aec8de70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-year&quot;)</value>
      <webElementGuid>a31e1529-d96a-4981-96fd-8087b80894c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='order-year']</value>
      <webElementGuid>b776d103-06ea-4150-87d3-1704d06f5c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-order']/div/div[7]/div[2]/select</value>
      <webElementGuid>5405f824-e5aa-40b1-94a5-1bbe41a0037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📅'])[2]/following::select[1]</value>
      <webElementGuid>97d03731-8d94-4d30-9acd-efdb0319d760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📅'])[1]/following::select[2]</value>
      <webElementGuid>bdb5ea8a-8ad2-433e-888d-2971826dc8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::select[1]</value>
      <webElementGuid>a574f36c-9141-4b38-9295-26fc179c687a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🍎'])[2]/preceding::select[1]</value>
      <webElementGuid>027288eb-5871-4cfa-95e6-328506be9293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/select</value>
      <webElementGuid>ba82ec67-b5bd-45dd-ba94-5141dd9ad07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'order-year' and (text() = 'Year2026202720282029203020312032203320342035203620372038203920402041' or . = 'Year2026202720282029203020312032203320342035203620372038203920402041')]</value>
      <webElementGuid>96b9708a-b19b-4ab2-be0f-4587ed2c2245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
