<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hitam</name>
   <tag></tag>
   <elementGuidId>9e767d5f-feb9-4bec-9b37-5b0d6807f1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detail-color-options']/label[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c4ba4ec-276d-490f-a86c-19d5fdd700d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color-name</value>
      <webElementGuid>f8cba83a-c750-42eb-9502-1eae2b41f4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitam</value>
      <webElementGuid>b778bdd4-5068-407e-b07b-f908250fa981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-color-options&quot;)/label[@class=&quot;color-option&quot;]/span[@class=&quot;color-name&quot;]</value>
      <webElementGuid>54510704-38ac-4faa-a741-a0ca87bf2e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail-color-options']/label[3]/span</value>
      <webElementGuid>24141b24-52a8-4b71-af76-e24b72e21915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Putih'])[1]/following::span[1]</value>
      <webElementGuid>b3286cbc-2dea-4ac2-906c-08f5c2abdd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merah'])[1]/following::span[2]</value>
      <webElementGuid>2f186284-3175-44ec-94f9-4e372626222c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biru'])[1]/preceding::span[1]</value>
      <webElementGuid>d12042dc-5bae-4d84-9916-a013394a6cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🛒 Add to Cart'])[1]/preceding::span[2]</value>
      <webElementGuid>409cdfca-5634-4a01-9511-fab92c278969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitam']/parent::*</value>
      <webElementGuid>4cc713f9-f035-4c15-aee0-608cb22884e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span</value>
      <webElementGuid>0359d52c-a664-43ba-89c4-7baa309d031f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hitam' or . = 'Hitam')]</value>
      <webElementGuid>c76c6c16-3b32-481b-afae-a18d1ceb1988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
